### ISSUE TITLE
Install issue (can neither install from .deb or .ipa package)

### ISSUE THREAD

**Issue by eliluong** [iandwelker/smserver#107]
I have iPad Pro gen1 on iOS 13.6 that was jailbroken with checkra1n and has Cydia installed.

I installed libmryipc and libsmserver via deb files. These appear in Cydia as installed. Next I installed OpenSSL because SMServer required it. I initially tried to install SMServer using the deb file via Filza, but it returned an error when trying to read key.pem. So I SSH into the iPad and ran `dpkg -i SMServer_0.7.3.deb` and this installed successfully. I rebooted and ran checkra1n again. Unfortunately, I do not have an app icon on the screen, even though SMServer appears in Cydia install list.

If I try to install the ipa from Filza, it returns an error: `Failed to open /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.KgR35O/extracted/Payload : No such file or directory`. I do have AppSync Unified installed (version 84.0) and other ipa have appropriately installed.

Thanks for your help.

**Comment by iandwelker** [comment]
I'd recommend installing the package via a package manager, such as Sileo or Zebra. I haven't yet tested installing it with dpkg extensively, so I can't be certain why it's not working. You can also just install it from the twickd repository, if you'd prefer not to go through the trouble of downloading a new deb for each update.

Also, as was brought up in #104, the `ipa` for versions 0.6.0 - 0.7.3 is corrupted; I messed up something in my build process for those versions. This should be fixed with version 0.7.4, though. so feel free to try that out if you'd still like to use the `ipa` instead of the deb.

**Comment by eliluong** [comment]
Thanks, installing Zebra and then the SMServer deb via Zebra did the trick (tried to load twickd repo initially, but like you said, fire took our their datacenter).
