### ISSUE TITLE
Question - How to run SMServer as a daemon

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#111]
I attempted to set up SMServer to run as a daemon by following [these instructions](https://github.com/iandwelker/smserver/issues/78#issuecomment-776873837), but I was unsuccessful. On version 0.7.3, it caused an infinite loop of crashes, but there were no more crashes on version 0.7.4 😃. This is what my SSH client looked like when I tried to run the commands
![Screenshot 2021-03-18 183430](https://user-images.githubusercontent.com/53708281/111706830-5c5b9d80-8819-11eb-8b9e-7ba9be31af08.png)

**Comment by iandwelker** [comment]
Yeah, uh I definitely checked everything extensively to make sure those commands worked, but they're not working for me now either. I'll look into this more to see if I can figure out the issue.

**Comment by iandwelker** [comment]
Update: turns out there were a lot of issues with that &mdash; I can describe them all if you want but it'll take quite a while so just suffice it to say this should be fixed with the next version.  Also shoutout to @sgtaziz, turns out the infinite crash from a few issues ago can be fixed with the `memorystatus_control` function he has in his main.swift file, so thanks to them for that.

**Comment by iandwelker** [comment]
This issue should be fixed with version 0.8.0. See the updated instructions in the [new daemon control file](https://github.com/iandwelker/smserver/blob/master/docs/com.ianwelker.smserver.plist)
