### ISSUE TITLE
Smserver automatically uninstalls libmserver and vice versa

### ISSUE THREAD

**Issue by jasonhkaiser** [iandwelker/smserver#125]
Whenever I try to install SMServer, it automatically uninstalls libsmserver and when I install libsmserver, it automatically uninstalls SMServer. I can’t have them on my device at the same time despite the dependency. It’s crazy!
![C5DE0AA5-B7A8-4E3B-935D-40E990A956C3](https://user-images.githubusercontent.com/40952710/116798729-ba3dff00-aac0-11eb-89dd-3354dd974c1a.png)
![E1A102EE-F43A-400B-B4FD-5DA0F28BCE4F](https://user-images.githubusercontent.com/40952710/116798730-bad69580-aac0-11eb-8d0a-cd06f4aeb3a1.png)
![D9F9DD16-C8B0-406D-8D8B-03869397582E](https://user-images.githubusercontent.com/40952710/116798731-bc07c280-aac0-11eb-82ea-61411ba768ae.png)
![47E47D9E-687A-4447-A3FC-93461DDFF82A](https://user-images.githubusercontent.com/40952710/116798733-bdd18600-aac0-11eb-8ac8-b1e9cb90eae3.png)

**Comment by AdamDempsey** [comment]
From the [smserver 0.8.0 Release Notes](https://github.com/iandwelker/smserver/releases/tag/v0.8.0):

"Built libsmserver into the .deb package so that it is no longer necessary as a dependency"

**Comment by jasonhkaiser** [comment]
Thank you



________________________________

**Comment by iandwelker** [comment]
Yeah, sorry I realize that I should probably be more clear about this in the README. The `.ipa` requires libsmserver to be installed, since I can't package it within an `ipa`, but the `deb` has it built-in, so it removes all other installations of libsmserver to make sure there are no conflicts. I'll update the README to reflect that clarification.
