### ISSUE TITLE
App crashing and server restarting after entering password on computer

### ISSUE THREAD

**Issue by mattp12** [iandwelker/smserver#2]
iPhone 8+ iOS 13.5
checkra1n

I followed the instructions and made sure that the dependencies were installed.
Crash log: https://pastebin.com/9BUVQSSD

Image of what shows in the browser immediately after entering in the password: 
![image](https://user-images.githubusercontent.com/8071273/87231830-6bd04000-c388-11ea-8877-198aa2e93923.png)

**Comment by iandwelker** [comment]
I've uploaded a new version of the .deb that I think may fix your problem. Try installing and running it. If it doesn't fix the problems, then please complete the following steps:

1. Open the app, turn on 'debug' in the settings, and completely close out of the app.
2. Install the package 'oslog' from your package manager
3. SSH into your device and run the command 'oslog --info | grep -i "smserver_app" > /var/mobile/Documents/smserver.log'. Leave this running through the next step.
4. Open the SMServer app, and try to load the server. Let it run until it crashes, or until you encounter your problem (and then a few seconds)
5. Kill the command that was launched in step 3.
6. If you're comfortable, grab the file from /var/mobile/Documents/smserver.log at u/Janshai on reddit. It may have some sensitive information (phone numbers of contacts, random texts), etc. but I won't keep that information. If you're not comfortable with that, you'll need to look through the log yourself and examine it to see if there are any warnings, issues of api misuse, etc.

I'll look at the log as soon as you send it over.

**Comment by mattp12** [comment]
I followed the instructions but the smserver.log file is empty after everything. I waited 10 seconds or so after the problem occurred.

When I run `oslog --info | grep -i "smserver_app"` in a terminal it outputs `os_log stream failed` so maybe this is why nothing is getting saved.

**Comment by iandwelker** [comment]
I uploaded a new .deb; it should fix part of your logging issue. That error that you got normally appears when you're not running oslog as root, so make sure that you're root, and run this next command: `oslog --debug | grep 'SMServer_app' > /var/mobile/Documents/smserver.log`. Once again, send the file to me if it's not empty.

**Comment by mattp12** [comment]
Alright here is the file. Sorry for the delay.
[smserver.log](https://github.com/iandwelker/smserver/files/4914078/smserver.log)

**Comment by iandwelker** [comment]
Alright, I think I may have fixed the issue. Could you download the latest versions of both the tweak and the app and let me know if they work?

**Comment by mattp12** [comment]
When trying to install this new SMServer app I get an error in the package manager log:
![4393](https://user-images.githubusercontent.com/8071273/87514582-76b8f800-c648-11ea-937d-04cc6a17a562.jpg)
I could however successfully install the tweak for it.

**Comment by iandwelker** [comment]
It appears that you're installing the .deb file, since it's set to run a chmod command right after installation. Since you're on checkra1n, I'd recommend that you try to install the .ipa instead (the chmod command is necessary for non-checkra1n devices to work correctly). The .ipa doesn't run the chmod command right after installation, so you should be able to install it without any issues. You'll have to remove the old package with your package manager first, but try that and let me know how it goes.

**Comment by mattp12** [comment]
I just installed the .ipa file and everything still crashed like before.
I ran `oslog --debug | grep 'SMServer_app' > /var/mobile/Documents/smserver.log` again and here is the log: https://pastebin.com/UjFP3WMQ.

Additionally, sometimes when opening the app, I get an error saying that it didn't get root.

**Comment by iandwelker** [comment]
If you have checkra1n, the warning that you didn't get root is totally fine and doesn't present an issue. 
I just uploaded a new .ipa;  could you install it, enable debug, restart the app, and then run that same command and try to access the server? Also, make sure you don't kill the command until at least a few seconds after the app has crashed.

**Comment by mattp12** [comment]
Log: https://pastebin.com/wHPR3xmC
I noticed that at the bottom it looks like more is being written but I let this command run for like 5 minutes after the crash. Hopefully what is there can suffice.

I also replaced phone numbers and last names with PhoneNumber and LastName in the log with regex, just in case you thought it was some issue with the code or something.

**Comment by iandwelker** [comment]
Ok, I just realized now that oslog seems to have a length limit on the number of characters it directly can output to a file, and that's why all your logs are incomplete; sorry I made you run that command so many times without realizing. Instead, could you:
1. SSH in
2. Run 'oslog --debug | grep "SMServer_app"' and let the output display as normal. Do not redirect into a file.
3. Try to run the app and let it crash
4. Wait until oslog has stopped outputting, then manually select and copy as much text as you can from your terminal window where oslog was outputting
5. Paste the oslog output into a text file and upload it again so that I can check it out.

Also, the filtering out for phone number and name is a good idea, feel free to keep doing so.

**Comment by mattp12** [comment]
Here is the file

[SMServer debug log 7-17-2020.txt](https://github.com/iandwelker/smserver/files/4940623/SMServer.debug.log.7-17-2020.txt)

**Comment by iandwelker** [comment]
Sorry, but this issue is very bizarre and I'm having quite a hard time identifying what could be causing it. I can identify exactly what line of code appears to be crashing this, according to the log. However, it's super innocuous and is successfully run hundreds of time before crashing. In case you're wondering, it's line 71 of ChatDelegate.swift:
```swift
if self.debug {
    self.log("full sql query: " + sqlString)
}
        
var statement: OpaquePointer? // <-- This line
        
if self.debug {
    self.log("opened statement")
}
```
The only other possible issue I can think of would be another async function running at the same time and crashing it conveniently at this time, but unless you're like opening the webpage on multiple browsers at the same time (or something absurd like that), there should be no other functions that could crash this. 
So I may have to put this issue on the backburner for a while, simply because I'm just not making progress on figuring out. I'll keep updating the repo with new packages either every day or every few days, so keep a watch out and if any of the new packages happen to fix it, let me know and we can close this.

**Comment by blanxd** [comment]
a few findings that might help along with this. Every time it happens, syslog gives this: `Fatal error: String index is out of bounds: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-1103.2.25.8/swift/stdlib/public/core/StringCharacterView.swift, line 79` After that the app gets torn down (simply looking with Console or deviceconsole or so). Now, enabling debug and looking for your printouts, it happens at different points (not only that L71 from @mattp12's logs), and it happens exactly at the same point every time, until I change the db, ie. send/receive a message, after which it starts crashing at some other location... The debug strings I've seen so far as the last ones before the crash (not pointing to line numbers on purpose here, but a few of the last lines if necessary):
```
parsing phone number for someName1
full sql query: SELECT c0First, c1Last from ABPersonFullTextSearch_content WHERE c16Phone LIKE "" LIMIT 0, 1;
opened statement
```
```
Finished iterating through chats for Optional("someName2")
```
```
Beginning to iterate through chats for Optional("halfOfSomeName3
```
```
full name for +5550000001 is Some Name4
```
```
Finished iterating through chats for Optional("+5550000002")
Beginn
```

All this I got with libsmserver 0.2.0-1+debug, smserver 0.2.0+debug18, ipXs 13.5 (u0 5.2.1). I have another one, ip8 13.5 (checkra1n) on which it runs fine. To be sure, I disabled all tweaks (with iCleaner), which aren't present in my ip8, to no effect.

But, I was able to get it working. Firstly I changed the initial chats & messages to load, to like 1 and 2, no effect. I then switched it to the Light theme, and voila. Then changed the chat and messages counts back, still working. Then toggled the theme back to Dark, it's still working with the Light theme. After some back and forth, respringing et al, looks like it works for me with the Light theme, the initial limits set to like 6 and 20 (instead of 60 and 200).

(I'm an objc person so I won't go looking too deep into the code myself here :)

**Comment by iandwelker** [comment]
This is really helpful; seems like it's an issue of trying to access array[-1] or something like that, but it's bizarre that it happens at different locations whenever you change the content of the database. Do you happen to have access to Xcode, or something with which you could set breakpoints before the crash and see if there are any variables that look incorrect or out of place? (e.g. index == -1, iterating through an array that is 0 length long, etc) 

Also, that's very bizarre that switching all those settings made things start to work again. I have no idea why switching the theme made it work, but I guess I'll keep that in mind and recommend it to other people who run into this. I'll keep this issue updated with any further developments, though.

**Comment by blanxd** [comment]
I was getting ready to dnl and build the project, noticed there had been some recent commits, checked the repo and updated to 0.2.0+debug19, and the lib as well. And guess what, it works without a hitch, no matter which theme and what numbers in the settings. So something must have cured it. I won't go try to find the issue that is solved now.

This is a great piece of soft!
(for one of my devices I'm logged in on my mac with the same appleID so Messages.app works great, but I'm using 2, and the other one has another ID so this system helps me with work related messaging, which is often technical so copy/paste et al will be making the life a bit more comfortable I hope)

**Comment by iandwelker** [comment]
Sweet! I'm glad it's working (and I appreciate the compliments :). @mattp12, do you think you could test out the latest version and let me know if it works for you too?

**Comment by mattp12** [comment]
It appears to work now. Thanks!

**Comment by iandwelker** [comment]
Glad to hear!
