### ISSUE TITLE
Always showing as new update in Cydia

### ISSUE THREAD

**Issue by shanep2300** [iandwelker/smserver#24]
I'm on 0.3.5 and it's still showing that there's a new update. It's been like this for a while now. Is there something on my end that needs to be done? Tried uninstalling and clearing out cache with iCleaner.

**Comment by iandwelker** [comment]
No, there isn't anything that you should have to do. This is an issue on either my side or the repo's side (though probably mine since it appears to not happen with any other package). I've been looking into this issue for a bit; I haven't found the fix yet but I'll update this task when I do find it.

**Comment by iandwelker** [comment]
This issue should be fixed now with 0.3.6. Could you upgrade and check to confirm?

**Comment by shanep2300** [comment]
As of right now, it’s fixed!

**Comment by iandwelker** [comment]
Alright, I'll close this issue. Feel free to reopen if it happens again.
