### ISSUE TITLE
SMServer crashing after starting server

### ISSUE THREAD

**Issue by ghost** [iandwelker/smserver#3]
Device model: iPhone 11 Pro Max
Jailbreak: Unc0ver 5.2.1
iOS Version: iOS 13.5
I installed the Deb and file from the github page and installed it through Filza.

So, I was able to launch SMServer a couple days ago, but then, when I tried to start the server, it just froze, and crashed after a minute. Now, I tried reinstalling it and it just crashes upon launch. I tried the iPA file, same thing. I go on Cr4shed and CrashReporter, and I don't see any logs there, either. I know this probably help you that much, and it's probbaly just something wrong with my phone, but who knows. If you have any suggestions on a fix for this, tell me and i'll try it. Thank you for making this! I really hope it works well for other people!

**Comment by iandwelker** [comment]
Try downloading and installing the .deb of the latest version + the latest version of libsmserver. It should have those issues fixed.
Also, I really appreciate the extensive information about the issue; it did help a lot.

**Comment by iFreezingFire** [comment]
still not working. i wiped the smserver user data with app manager, and now it opens, so that's good. the one problem is it still just freezes when i try to start it, and there's literally no crash log still. i have the updated version of both smserver and libsmserver. also now there is a pop up saying i didn't get root when i opened it up, which seems pretty important. sorry that you don't have that much to work with man, it's probably really hard to fix this with the little information you have.

**Comment by iandwelker** [comment]
Nah, you're giving me good information. I'll need a bit more information, though:
 - Did you install the .deb or .ipa this time?
 - Please SSH into your device, run the command `ls -la /Applications/SMServer.app/SMServer`, and then paste the output here
 - Also, please complete the following steps:
1. SSH into your device
2. Run `oslog --debug | grep "LibSMServer_app"` , and don't end this command until I state so in step 4.
3. Respring your device, and then open the app and try to start the server. Let it crash, if that's what happens. 
4. Wait until the oslog command has stopped outputting, then cancel the command (hit Ctrl+C) and manually copy the output into a text file, and upload it on somewhere like pastebin where I can look at it.

**Comment by iFreezingFire** [comment]
i installed the ipa and deb, and had the same problem. also, I don't know what's happening now, but literally when i ran the command from my pc, my phone just goes completely unresponsive. this has to be a problem with my phone. i tried doing the command for more than an hour, even with different ssh programs, and this is the only result. i don't really know what to do. i do kind of believe that the problem that i'm having is just a problem with my phone, but i don't really know. if you can, try to find someone with the same device (iPhone 11 Pro Max) running iOS 13.5 with the U0 jailbreak, and see if they have the same problem.

**Comment by iandwelker** [comment]
Sorry, I forgot to specify that you need to install the package 'oslog' with your package manager before you run that command, but with or without the package, running the command shouldn't freeze your phone. I'm switching over my personal device to u0 soon so I can test it out, though; I'll update you if I find what the error is.

**Comment by iFreezingFire** [comment]
yeah i had oslog installed. but yeah update me if you find any fixes man. thanks for working with me and making this, i hope a lot of people appreciate it! good luck, man.

**Comment by iandwelker** [comment]
I fixed some issues with unc0ver in the latest version + tested it on an unc0ver 6s and it seems to work fine; try it out and let me know if it fixed anything for you.

**Comment by iFreezingFire** [comment]
still didn't do anything. do you think it could be tweak interference? i don't have too many tweaks and can provide you with one if you want.

**Comment by iandwelker** [comment]
Sorry to take so long to respond; you could provide me with a tweak list, but I really wouldn't have a good way to test those tweaks out since some may be paid or require dependencies that i can't get, etc. It seems like that could be a possible culprit, though, so if possible, maybe you could try running through disabling tweaks to see if you can identify any that are causing issues? It would be a relief to find out that there's just a tweak that conflicts with this.

**Comment by iandwelker** [comment]
This issue's creator has deleted their account, so there's no way for me to verify if it's fixed after any improvements. Closing issue.
