### ISSUE TITLE
App keeps closing

### ISSUE THREAD

**Issue by blimeybloke** [iandwelker/smserver#32]
I need to keep starting the app on my phone.  It seems that after about 30 seconds of screen turning off, the server will stop.  When I unlock phone, the app is not running anymore.  I have tried to start the server and just set phone down.  I have also tried to turn on and off backgrounding but neither seemed to help.  

I have latest pull from your repo as of 9-2 (v0.3.7)
I am running on an older iphone SE, and 13.6.1

Cheers

**Comment by iandwelker** [comment]
See #18 &mdash; This is an acknowledged issue. It's proving difficult to figure out, though, so it may take a while to fix. If this issue appears to be the same thing as 18, feel free to close it and watch 18 instead. However, if you feel that this is a different issue or has a different root cause, we can leave this open as well.

**Comment by blimeybloke** [comment]
Thanks, you are correct, same as 18.  Closing this one.
