### ISSUE TITLE
[Request] The ability to pin/manually select which messages are loaded by default.

### ISSUE THREAD

**Issue by connervieira** [iandwelker/smserver#4]
So far, the one (mild) issue I've found is that it takes a long time for the web interface to load, since it has to load so many chats, each with a large amount of images. The ability to change the amount of initial chats loaded is helpful, but I think the ability to pin messages, or select messages to be loaded manually would make it a lot easier to only select the messages you need, unless you load more.

**Comment by iandwelker** [comment]
I can look into pinning messages; that probably won't come soon, though, since there are more crucial features that are yet to be added. However, the web interface doesn't actually load any messages until you select a conversation. It only loads the conversation list initially, and then loads the texts/images for each conversation when you select them in the conversation box on the left. So, if I'm understanding you correctly, the 'select messages to be loaded manually' is already implemented. If I'm not understanding correctly, though, let me know.

**Comment by connervieira** [comment]
No, you are understanding me correctly. I appreciate the clarification. I was under the impression that all of the messages for each of the chats were loaded in the background. That makes a lot of sense, and of course, I understand that need to get the core features working before extra functionality can be added.
I appreciate all the great work you're doing for this!

**Comment by iandwelker** [comment]
No problem :) I think I'm going to close this issue for now, since I'm not planning on working on pinned chats until an iOS 14 jb is out (so that I can just use the built-in data on what chats are pinned). I'll reopen it when that happens, though, and update on my progress.

**Comment by CSab6482** [comment]
https://github.com/sgtaziz/WebMessage/issues/56#issuecomment-788059106
