### ISSUE TITLE
Web interface will keep loading FOREVER

### ISSUE THREAD

**Issue by luixiuno** [iandwelker/smserver#41]
Jailbreak: Oddessey. Package Manager: Sileo. iOS Version: 13.3, 13.3.1?

Installed on Twickd Repo

**Comment by iandwelker** [comment]
Could you be more specific about what the issue is? If you can't connect to the web interface, then please answer the following questions:
1. Have you made sure to install all of the dependencies (specifically `libsmserver` and `libMRYIPC`)?
1. Did you start the server with the green button on the bottom left of the app?
1. Are you connecting to the right address with regard to using `https://` vs `http://`?
1. Are your host and client devices on the same LAN/WLAN networks?
1. Did you verify that neither device's firewall is blocking the connection?

**Comment by vugi99** [comment]
Try to disable SSL and connect with http://

**Comment by iandwelker** [comment]
This issue has been open for over a month with no response from its creator, so I'm going to close it. If you are still running into this problem or would like to provide more information, feel free to re-open this.
