### ISSUE TITLE
[Feature Request] Emoji Picker

### ISSUE THREAD

**Issue by AdamDempsey** [iandwelker/smserver#42]
Thanks for a brilliant tweak, have just sent a donation to Yemen Relief as a thanks :)

Works perfectly for me, only suggestion I have is an emoji picker to allow easily adding to messages, not sure how complicated that is considering different iOS versions have different emoji but thought would ask if possible.

Thanks again!

**Comment by iandwelker** [comment]
I'm glad things are working well :)

I also appreciate the suggestion, but I actually thought about this a bit back and I don't think I'm planning on implementing this feature, for a few reasons:
1. Most operating systems have easy-to-access emoji pickers already built in to them. On Mac, you can summon one by hitting Cntrl+Cmd+Space, on Windows you can summon one with Win+. or Win+; and on Linux there are multiple easy ways to install an emoji picker that works with your distribution (one is even built in to Ubuntu). So adding this feature would be somewhat extraneous and unnecessary.
2. Emoji pickers are not easy to make, meaning that I would probably have to use a third-party picker, meaning that it would only work if one was connected to the internet. I would prefer to build this app so that it works just fine with or without internet, so that anyone who is worried about outgoing connections is free to block internet connections from this app and still have everything work fine. Adding something that requires the internet to function at all would go against this, and make internet connectivity a requirement. I'm aware that I'm currently font awesome scripts from an online cdn (which goes against what I just said), but I plan on removing them soon so that internet is not required for any functionality of the app.

If you have any other reasons that you think I should consider actually adding an emoji picker, please let me know and I'll think about it. I'm open to persuasion.

**Comment by AdamDempsey** [comment]
I never knew about the keyboard shortcuts to bring up the native emoji picker, that solves the need for me :)
