### ISSUE TITLE
Feature Request — Ability to click on the chat that you are currently in to go back into the "Select a chat on the left to view your messages :)" screen

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#51]
I like having this tab open at all times, but having a particular chat open while I'm on another tab marks the messages as read and sometimes makes me miss notifications. I solve this by refreshing the page to go back into the home screen, but in the old Remote Messages tweak I used, the home screen could be accessed again by clicking on the chat you are currently in.
Would this be worth implementing? I saw another request to simply not mark the chat as read while the tab was not active. That could work nicely too but I like the ability to return to the homescreen. If it's too much hassle to implement or it's solving a problem that doesn't exist, I am okay with this request being closed.

**Comment by CSab6482** [comment]
I also understand that I can turn off the "Mark as read" setting, but that is the same amount of resetting and refreshing as it is for me to refresh the page, and I like my messages being marked as read no matter where I open them from.

**Comment by iandwelker** [comment]
The app is actually already supposed to mark the chat as read if you don't have the tab focused, however while working on the next version I realized that some of my logic in the web interface was faulty, so there are definitely some issues with conversations being marked as read or not marked as read when that shouldn't be the case, or showing notifications or not showing notifications, etc. All those issue should be theoretically fixed in the next version.
With regard to returning to the home view: I would prefer to keep it so that you can reload a conversation by simply clicking on its box in the view on the left (so that you don't have to reload and re-select it), but I could implement functionality to allow you to return to the home page if you click on the "SMServer" title up in the top left. Would that work for you?

**Comment by CSab6482** [comment]
That would be perfect. Thanks so much for your reply and for retaining so much functionality in the server.
