### ISSUE TITLE
0.5.4 No actual messages

### ISSUE THREAD

**Issue by blimeybloke** [iandwelker/smserver#58]
I just upgraded to the newest version, started the app on the phone.  Reloaded the web interface, and logged in.  I see all my contacts on the left, but no actual messages from anyone.  If I click "+ More Texts" it does not do anything.

**Comment by iandwelker** [comment]
If you view your browser console (Right click > Inspect (or 'Inspect Element') > Console), does it show any errors? Also, what browser are you using, and have you ran an ldrestart since updating?

**Comment by blimeybloke** [comment]
I have tried 2 browsers and the old version worked.  However, I am not sure what you mean by ldrestart?  How would I do that?
thanks

**Comment by blimeybloke** [comment]
This may help:
(index):389 Uncaught (in promise) ReferenceError: chats is not defined
    at printListOfTexts ((index):389)
    at getTexts ((index):660)

**Comment by iandwelker** [comment]
Ok, I've found the issue, and I'll have it fixed in the next version. If you'd like to fix it yourself, you can turn off 'debug' in the app's settings and everything will work fine, or you can also open the file `/Applications/SMServer.app/html/chats.html` and, on line 390, change `String(chats.length)` to `String(texts.length)`

**Comment by blimeybloke** [comment]
Thanks, I turned debug mode off, did ldrestart, and all was working.
Cheers!

**Comment by iandwelker** [comment]
Version 0.6.0 of SMServer is out with this fix. Closing issue
