### ISSUE TITLE
Tapbacks duplicate and graphical glitch blacks out part of the chat (SMServer 0.6.3, iPhone 6S iOS 14.2, odysseyn1x 2.8)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#67]
![Duplicate Tapbacks](https://user-images.githubusercontent.com/53708281/103161281-5b344a80-47ad-11eb-8165-fc089bf3fb56.jpg)
![Duplicate Tapbacks + Black Rectangles](https://user-images.githubusercontent.com/53708281/103161282-5c657780-47ad-11eb-827d-b15c9026af78.jpg)
The tapbacks are normal, but then they duplicate whenever another message or tapback is sent or received. After a certain amount of duplications, the screen blacks out as well.

**Comment by iandwelker** [comment]
Yeah, I did notice the issue of tapbacks duplicating instead of replacing soon after I released the latest version -- I'll have that fixed by the next version. However, I hadn't yet run into the issue where the screen blacks out. Hopefully that'll be fixed when the tapbacks are prevented from duplicating.

**Comment by davr** [comment]
I also get the duplicate tapbacks, also get the screen blanking out -- scrolling up and then down again is a pretty easy way to reproduce it once it starts happening. Switching to another chat and back seems to fix it for a while. I also have a 3rd glitch where the usernames are in the wrong place sometimes, on the most recent chat message the sender's name will appear below the message instead of above it, making it seem like the message belongs to the previous person.

**Comment by iandwelker** [comment]
This bug has been fixed in version 0.7.0, so I will close this issue report. Feel free to reopen it if you're still running into something.
