### ISSUE TITLE
Does not update message logs when sent from a Mac/iPhone

### ISSUE THREAD

**Issue by midi1996** [iandwelker/smserver#76]
Here the video of the issue:

https://streamable.com/qbmutu

Basically sending messages from your iPhone or macOS wont show up in the chat log in SMServer unless you refresh the webpage or switch users.

**Comment by iandwelker** [comment]
Yes &mdash; I've been aware of this for a while, but have yet to find a good solution for it. The issue is simply that I've yet to find an easy/elegant solution to detect, with a high level of accuracy, when texts are sent outside of SMServer. For more technical detail, read below, but tl;dr is that I'm working on it and would like to get this fixed as well.

For detecting when the host device receives a chat, libsmserver creates a notification observer for the notification name `__kIMChatMessageReceivedNotification`. This observer is then notified every time the device receives a new message, and sends it to SMServer to be parsed correctly. There is a similar notification that is *theoretically* posted every time a message is sent from the host device's iMessage account (and I think phone number as well) with the name `__kIMChatRegistryMessageSentNotification`. I have tried creating a notification observer for this notification in every way I know how: in SpringBoard and many other processes, while connected to the IMDaemon and while disconnected, on the main thread and on background threads, etc, and I have yet to find a way to actually listen to when this notification is posted. I also say that it is *theoretically* posted because every time that I try to work on this, the system randomly stops posting this notification about a half hour or hour into working on this, so I can rarely make any progress on figuring it out. It's been tough, but I have been slowly making progress, and I hope to have this fixed soon (though how soon, I cannot say).

**Comment by CSab6482** [comment]
https://github.com/sgtaziz/WebMessage/issues/42#issuecomment-779954813

**Comment by iandwelker** [comment]
Alright, it's taken quite a while but I think I've got this one fixed -- [SMServer commit](https://github.com/iandwelker/smserver/commit/594d6a7c5646acf86be613979c805e6c33c12b0c) and [libsmserver commit](https://github.com/iandwelker/libsmserver/commit/fab7711fa65db0b939fbc92ff9ce0d2b608d45c0)

**Comment by CSab6482** [comment]
Can you test for [this issue](https://github.com/sgtaziz/WebMessage/issues/92)?

**Comment by iandwelker** [comment]
> Can you test for this issue?

Looks like I'm not running into that issue; not quite sure why it's being weird for sgtaziz.

**Comment by CSab6482** [comment]
I still have to click out of a chat and then back into it to see messages that I sent from my Mac.
![Untitled](https://user-images.githubusercontent.com/53708281/116648269-99ec3400-a94a-11eb-9702-572216ac744f.png)
I sent my "Don't mind me" text from my Mac, and I had to click out of the chat and back into it to see the message. I also sent a tapback from my Mac that you can see hasn't shown up in this screenshot yet. Also, for some reason, my contact's name was displayed under the message.

**Comment by CSab6482** [comment]
https://github.com/iandwelker/smserver/issues/101#issuecomment-830665407
