### ISSUE TITLE
ERROR: Please use llvm >= 12.0.0 to compile

### ISSUE THREAD

**Issue by TokeyChan** [iandwelker/smserver#77]
Hello!

I am not quite sure if I am doing this whole installation thing correctly (its the first app I am trying to install on my jailbroken iPhone)
I cloned the repository on my mac, I did `cd smserver` then `./make.sh -dn`, it asked for a password but then showed this error:

`ERROR: Please use llvm >= 12.0.0 to compile`

I tried to install llvm via homebrew, but when I run `brew info llvm` it shows that llvm is still at 11.0.0_1

Any ideas?

**Comment by iandwelker** [comment]
Ideally, you should be installing llvm through xcode commandline tools, not homebrew. I'd recommend uninstalling llvm from brew, and then installing xcode command line tools with `xcode-select --install`.

If you already have xcode command line tools installed, I'd still recommend uninstalling llvm from homebrew, and then check to make sure that you're using xcode version 12.0 or higher. You can compile this package with xcode < 12.0, but I've noticed that it causes some weird UI bugs, so that's why I put the check in the build script to encourage people to use xcode >= 12.0.

If you don't care and would like to compile it with the xcode version you currently have, then you can just open `make.sh` in your text editor and remove the line that says `[ ${llvm_vers} -lt 1200 ] && err "Please use llvm >= 12.0.0 to compile"`

**Comment by TokeyChan** [comment]
Thanks for your quick response! 

I deleted llvm via homebrew but I failed to update my Xcode to 12.0 since my OS is too old to run it. 
Instead I did what you said and deleted the line in `make.sh`.

It worked that time, but I got the next error:
`error: No profiles for 'com.ianwelker.smserver' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.ianwelker.smserver'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'SMServer' from project 'SMServer')`

Can this be due to my old Xcode version? (11.3)
Should I maybe try to install an older version of your repository?

**Comment by iandwelker** [comment]
No, this issue is due to me not providing proper instructions &mdash; What you'll need to do now is open `SMServer.xcworkspace` in Xcode, select the project, click on the 'signing and capabilities' tab, and select a certificate from the 'team' dropdown menu. Once you've done this, re-run the script and it *should* work fine

**Comment by iandwelker** [comment]
As of a few versions ago, the make script should give a more detailed explanation about this error, and allows provisioning updates so that you shouldn't have to open up the workspace and set the certificate yourself. Closing.
