### ISSUE TITLE
Group message loads out of order, undefined sender

### ISSUE THREAD

**Issue by astra-io** [iandwelker/smserver#80]
Contact names on messages in a group chat are usually out of order on receival - usually offset by an 'undefined' user. The rest of the messages then have offset senders.
Refreshing fixes this problem, but quite annoying. 
I'll try and get a screenshot of this when I receive more messages.

**Comment by iandwelker** [comment]
Sorry, I don't think I understand exactly what you mean -- if you could get a screenshot to show what's happening, that would help a lot.

**Comment by gnawh** [comment]
![1](https://user-images.githubusercontent.com/26584539/105947804-9e890f80-601e-11eb-956e-5d28ad2cc6ee.png)
![2](https://user-images.githubusercontent.com/26584539/105947800-9e890f80-601e-11eb-95a1-abd5c1745453.png)

Remembered to take a screenshot of it. 1 is how chats come in, 2 is how it should be (after a refresh)

**Comment by CSab6482** [comment]
I also have problems with undefined link previews (mainly for music).

**Comment by iandwelker** [comment]
So I ran into this issue myself a few times -- I think it spawns from a group message 'event' (such as the profile picture or name changing) showing as a text, but offsetting things since it has no sender. I pushed a fix with version 0.7.2, but I'm not 100% certain it will fix the issue. @gnawh could you let me know if you're still seeing this issue once you update?

**Comment by CSab6482** [comment]
@astra-io

**Comment by iandwelker** [comment]
This issue's been stale for a bit without interaction from OP, and I haven't run into any issues with this recently, so I'm closing it.
