### ISSUE TITLE
Request for a toggle to automatically open links in a new tab

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#83]
I was scrolled up very high up in a chat and clicked a link, but since it opened in the tab I had SMServer opened in, I had to scroll back up to get to where I was. Usually I hold down Ctl before opening a link anyways, but this time I clicked by accident. Could this be set as a toggle within the iPhone app?

Also, I saw on the main page that there will be an option to run the server as a daemon, will there be any significant difference between that and using the app?

**Comment by iandwelker** [comment]
I can definitely look into adding that... I honestly prefer that as well and I feel like the majority of the user base may agree so honestly I think I'll just add this and then change it to an optional thing if anyone complains.

Also, with regards to the daemon/cli tool: It's actually the exact same thing as the SMServer app (same binary is run), but the app now just checks if any command line arguments were passed to it. So if you run it with any command line arguments  (e.g. through ssh in a shell), it acts like a cli app, but if you run it with no command line arguments, it opens up the GUI and runs like a regular iPhone app. I've tested it myself, though, and you can set it up as a daemon so that it automatically runs as soon as you boot up your phone (well, ldrestart or userspace reboot) and stays in the background forever without you having to do anything.

**Comment by iandwelker** [comment]
Alright, I've added this in version 0.7.2; it's been uploaded to twickd and should be available to install soon. I'll close this. Let me know if the feature doesn't work.
