### ISSUE TITLE
Cannot display a message that is just a space

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#90]
I was talking to someone and they were telling me about how something left them speechless, so they sent me a message that was just " ", which displays as a small blank blue bubble on iOS (the more spaces, the longer the bubble). This message didn't display on my Android phone with the BlueBubbles app, or any of my other iMessage forwarding apps, so I sat there confused waiting to receive a message only to check my iPhone and see that it was a blank. Of all the apps with this issue, SMServer was the only one that allowed me to send a blank, and SMServer and WebMessage both displayed a timestamp for the blank message.
![Blank SMServer](https://user-images.githubusercontent.com/53708281/108304180-713f0580-7175-11eb-9ddb-24dc0f9d590c.JPG)
![Blank iOS](https://user-images.githubusercontent.com/53708281/108304220-887df300-7175-11eb-80f5-3169b699b432.PNG)
See issues [here](https://github.com/BlueBubblesApp/BlueBubbles-Android-App/issues/786), [here](https://github.com/BlueBubblesApp/BlueBubbles-Desktop-App/issues/155), and [here](https://github.com/sgtaziz/WebMessage/issues/48)

**Comment by iandwelker** [comment]
Yeah, so this is kinda a funky issue -- SMServer automatically does not display a text if it is only whitespace. This is due to the fact that apple inserts weird, sometimes (but only sometimes) invisible characters (that are not traditional whitespace like spaces, tabs, or newlines) into the body of every text that contains attachments. So if I do display every message, every message that has attachments will have a few nonsense characters at the beginning of its message, which I would like to avoid. 

I guess I could allow empty texts when they have no attachments? I'd have to test that out for a bit, though, to make sure there are no other weird effects. Also, that would mean that you could not send an attachment with just a space, so this wouldn't be a complete solution. I'll keep looking into it.

**Comment by iandwelker** [comment]
Update: I lied; I thought it was different characters on each message, turns out it's just the same character each time. I just filtered them all out with `string.replacingOccurrences(of: "\u{fffc}", with: "", options: NSString.CompareOptions.literal, range: nil)` in the host, and now texts that are only spaces show just fine in the web interface. This will be fixed with the next update.

**Comment by CSab6482** [comment]
> Update: I lied; I thought it was different characters on each message, turns out it's just the same character each time. I just filtered them all out with `string.replacingOccurrences(of: "\u{fffc}", with: "", options: NSString.CompareOptions.literal, range: nil)` in the host, and now texts that are only spaces show just fine in the web interface. This will be fixed with the next update.

That's great to hear! Will the other developers be notified of this through the link mentions?

**Comment by iandwelker** [comment]
I can let them know if they ran into this issue for the same reasoning as me; however, this may be a completely different bug in their apps, so I'll wait to see if they're running into the same issue, and let them know my solution if so.

**Comment by iandwelker** [comment]
Alright, I've updated the app and it should include this fix &mdash; try it out and let me know if this issue is fixed for you as well.

**Comment by CSab6482** [comment]
It is fixed, however all blank messages show up only as one space on SMServer instead of however many there actually are (whether it be 1 or 100). Honestly, it isn't that big a deal since either way the message will be conveyed, but I just want to know if it's okay to close this issue like that.

**Comment by iandwelker** [comment]
Ah yeah, I know what my issue is &mdash; html tags with only whitespace don't show unless you replace them with explicitly viewable whitespace (e.g. `&nbsp;`). I just replaced the first space in each message with a viewable space, I should've replaced each space with `&nbsp;`. This'll be fixed in the next version.

**Comment by iandwelker** [comment]
Version 0.7.4 is out on twickd.
