### ISSUE TITLE
Cannot download files in Chromium browsers (0.7.3)

### ISSUE THREAD

**Issue by CSab6482** [iandwelker/smserver#94]
![cannot download](https://user-images.githubusercontent.com/53708281/108611650-92d70180-73ae-11eb-8d0d-49f92110965c.JPG)
![Edge no download](https://user-images.githubusercontent.com/53708281/108611651-92d70180-73ae-11eb-90d6-74276a99a804.JPG)
It works as expected in FireFox, the Edge Message is cut off but reads "Couldn't download - No file"

**Comment by CSab6482** [comment]
This problem also occurs when opening web preview images in a new tab and trying to download them, however, opening contact and group chat images in a new tab and downloading them does work.
Also, why are the web previews .pluginPayloadAttachment files. Is this what natively is on the iPhone?

**Comment by iandwelker** [comment]
Yes, I should be able to fix this ([solution](https://stackoverflow.com/questions/57909738/download-doesnt-work-when-using-code-206-partial-content)) -- I mainly test with Firefox, so I didn't run into this. It fails with attachments but not with group chat pictures because only attachments send the Partial Content header.

Also, with regard to `.pluginPayloadAttachment` files -- that is what they are stored as in the phone's database & file system. I'm not quite certain why they make that distinction from regular image files, but that's just what they're stored as.

**Comment by iandwelker** [comment]
Version 0.7.4 is out on twickd.
